config/routes.rb
Rails.application.routes.draw do
  get "pages/home"
  get "pages/about"
  get "pages/contact"
  get "pages/faq"
  get "pages/privacy_policy"
  get "pages/legal_notice"
  get "pages/terms_and_conditions"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "collections#index"

  # users
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  # collections
  resources :collections

  # categories
  resources :categories

  # products
  resources :products do
    resources :cart_items, only: [ :create ]
  end

  # carts
  resources :carts do
    resources :cart_items, only: [ :destroy ]
  end

  get "cart/:id/checkout" => "carts#checkout", as: :cart_checkout
  get "cart/success" => "carts#success", as: :cart_success
  get "cart/cancel" => "carts#cancel", as: :cart_cancel

  namespace :admin do
    root "dashboard#index"
    resources :users
    resources :collections
    resources :categories
    resources :products
    resources :carts
    resources :cart_items
  end
end

app/models/collection.rb
class Collection < ApplicationRecord
  # id, name, created_at, updated_at
  has_one_attached :photo
  has_many :collection_assignments, dependent: :destroy
  has_many :products, through: :collection_assignments

  validates :name, presence: true, uniqueness: true

    # ransack search
    def self.ransackable_attributes(_auth_object = nil)
      %w[name id created_at updated_at]
    end

    def self.ransackable_associations(_auth_object = nil)
      %w[products]
    end
end

app/controllers/admin/collections_controller.rb
class Admin::CollectionsController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [ :show, :edit, :update, :destroy ]

  def index
    @collections = Collection.all
  end

  def show
    @q = @collection.products.ransack(params[:q])
    @products = @q.result(distinct: true).order(:name)
    @categories = Category.all.sort_by do |category|
      [ params.dig(:q, :category_id_in)&.include?(category.id.to_s) ? 0 : 1, category.name ]
    end
  end

  def new
    @collection = Collection.new
  end

  def create
    @collection = Collection.new(collection_params)

    if @collection.save
      redirect_to @collection, success: "La Collection a été créée avec succès"
    else
      render :new, alert: "Echec de la création de la Collection"
    end
  end

  def edit
  end

  def update
    if @collection.update(collection_params)
      redirect_to @collection, success: "La Collection a été modifiée avec succès"
    else
      render :edit, alert: "Echec de la modification de la Collection"
    end
  end

  def destroy
    if @collection.destroy
      redirect_to collections_path, notice: "La Collection a été supprimée avec succès"
    else
      redirect_to @collection, alert: "Echec de la suppression de la Collection"
    end
  end

  private

  def collection_params
    params.require(:collection).permit(:name, :description, :photo)
  end

  def set_collection
    @collection = Collection.find(params[:id])
  end
end

app/helpers/admin/collections_helper.rb
module Admin::CollectionsHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/edit.html.erb
<h1 class="text-center text-2xl font-bold my-4">
  Modifier la collection
</h1>

<main>

  <%= form_for @collection, html: { class: "space-y-4" }  do |f| %>

    <div class="md:w-1/2 mx-auto space-y-1">
      <%= f.label :name, "Nom de la collection", class: "block" %>
      <%= f.text_field :name, placeholder: "T-shirts", class: "bg-gray-600 w-full rounded-sm" %>
    </div>

    <div class="md:w-1/2 mx-auto space-y-1">

      <%= f.label :photo, "Photo de la collection", class: "block" %>
      <%= f.hidden_field :photo, value: @collection.photo.attached? ? @collection.photo.signed_id : nil %>
      <%= f.file_field :photo, as: :file, class: "w-32 h-32 object-cover rounded-sm",  direct_upload: true, class: "bg-gray-600 w-full rounded-sm" %>

      <% if @collection.photo.attached? %>
        <div class="mt-2 flex justify-center">
          <%= cl_image_tag @collection.photo.key, class: "w-32 h-32 object-cover rounded-sm" %>
        </div>
      <% end %>

    </div>

    <div class="text-center space-x-4">

      <%= f.submit "Modifier la collection", class: "cursor-pointer bg-blue-800 px-4 py-2 rounded-sm hover:bg-blue-700 transition hover:duration-300 " %>
      <%= link_to "Supprimer", collection_path(@collection), data: {turbo_method: :delete, turbo_confirm: "Supprimer la collection ?"}, class: "bg-red-800 px-4 py-2 rounded-sm hover:bg-red-700 transition hover:duration-300" %>

    </div>

  <% end %>

</main>

app/views/collections/index.html.erb
<h1 class="text-center text-2xl font-bold my-4">
  Toutes les collections
</h1>

<%= link_to 'Créer une nouvelle collection', new_collection_path, class: "bg-blue-800 px-4 py-2 rounded-sm hover:bg-blue-700 transition hover:duration-300" %>

<main class="p-10">
  <%= render 'collections/components/collections-grid', collections: @collections %>
</main>

app/views/collections/new.html.erb
<h1 class="text-center text-2xl font-bold my-4">
  Nouvelle collection
</h1>


<main>

  <%= form_for @collection, html: { class: "space-y-4" }  do |f| %>

    <div class="md:w-1/2 mx-auto space-y-1">
      <%= f.label :name, "Nom de la collection", class: "block" %>
      <%= f.text_field :name, placeholder: "T-shirts", class: "bg-gray-600 w-full rounded-sm" %>
    </div>

    <div class="md:w-1/2 mx-auto space-y-1">

      <%= f.label :photo, "Photo de la collection", class: "block" %>
      <%= f.hidden_field :photo, value: @collection.photo.attached? ? @collection.photo.signed_id : nil %>
      <%= f.file_field :photo, as: :file, class: "w-32 h-32 object-cover rounded-sm",  direct_upload: true, class: "bg-gray-600 w-full rounded-sm" %>

      <% if @collection.photo.attached? %>
        <div class="mt-2 flex justify-center">
          <%= cl_image_tag @collection.photo.key, class: "w-32 h-32 object-cover rounded-sm" %>
        </div>
      <% end %>

    </div>

    <div class="text-center">
      <%= f.submit "Créer la collection", class: "cursor-pointer bg-blue-800 py-2 px-4 rounded-sm" %>
    </div>

  <% end %>

</main>

app/views/collections/show.html.erb
<h1 class="text-center text-2xl font-bold my-4">
  <%= @collection.name %>
</h1>

<div class="text-center space-x-4">
  <%= link_to "Modifier", edit_collection_path(@collection), class: "bg-blue-800 px-4 py-2 rounded-sm hover:bg-blue-700 transition hover:duration-300" %>
  <%= link_to "Supprimer", collection_path(@collection), data: {turbo_method: :delete, turbo_confirm: "Supprimer la collection ?"}, class: "bg-red-800 px-4 py-2 rounded-sm hover:bg-red-700 transition hover:duration-300" %>
</div>

<div class="flex justify-center my-4">
  <% if @collection.photo.attached? %>
    <%= cl_image_tag @collection.photo.key, width: 240, height: 240, class: "rounded-lg" %>
  <% else %>
    <p>Pas de photo</p>
  <% end %>
</div>

<main class="grid grid-cols-4 gap-4 my-8">

  <%= render 'collections/components/aside-filter', q: @q, categories: @categories, collection: @collection %>
  <%= render 'products/products-grid', products: @collection.products %>

</main>