config/routes.rb
Rails.application.routes.draw do
  get "pages/home"
  get "pages/about"
  get "pages/contact"
  get "pages/faq"
  get "pages/privacy_policy"
  get "pages/legal_notice"
  get "pages/terms_and_conditions"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "collections#index"

  # users
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  # collections
  resources :collections

  # categories
  resources :categories

  # products
  resources :products do
    resources :cart_items, only: [ :create ]
  end

  # carts
  resources :carts do
    resources :cart_items, only: [ :destroy ]
  end

  get "cart/:id/checkout" => "carts#checkout", as: :cart_checkout
  get "cart/success" => "carts#success", as: :cart_success
  get "cart/cancel" => "carts#cancel", as: :cart_cancel

  namespace :admin do
    root "dashboard#index"
    resources :users
    resources :collections
    resources :categories
    resources :products
    resources :carts
    resources :cart_items
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user

  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items

  validates :total_price, presence: true

  validates :total_price, numericality: { greater_or_equal_than: 0 }
  # status: pending, awaiting_payment, paid, shipped, abandoned
  validates :status, presence: true
  validates :status, inclusion: { in: %w(pending awaiting_payment paid shipped abandoned) }
end

app/controllers/admin/carts_controller.rb
class Admin::CartsController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def index
    @carts = Cart.all
  end

  def show
    @user = current_user
    @cart = @user.carts.find_by(status: "pending")
  end

  def checkout
    @user = current_user
    @cart = @user.carts.find_by(status: "pending")
    @cart.update(status: "awaiting_payment")
    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      mode: 'payment',
      billing_address_collection: 'required',
      success_url: cart_success_url,
      cancel_url: cart_cancel_url,
      line_items: @cart.products.map do |product|
        {
          price: product.stripe_price_id,
          quantity: 1
        }
      end
    )
    redirect_to session.url, allow_other_host: true
  end

  def success
    @user = current_user
    @cart = @user.carts.find_by(status: "awaiting_payment")
    @cart.update(status: "paid")
    redirect_to cart_path(@cart), notice: "Votre paiement a bien été effectué"
  end

  def cancel
    @user = current_user
    @cart = @user.carts.find_by(status: "awaiting_payment")
    @cart.update(status: "pending")
    redirect_to cart_path(@cart), notice: "Votre paiement a été annulé"
  end
end

app/helpers/admin/carts_helper.rb
module Admin::CartsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<%# display my cart %>

<h1 class="text-center text-2xl font-bold my-4">
  Mon Panier
</h1>

<main id="actual-cart-items">

  <div class="md:w-1/2 mx-auto space-y-4">

    <% if @cart.cart_items.any? %>
      <table class="w-full table-auto">

        <thead>
          <tr>
            <th class="text-center">
              Articles
            </th>
            <th class="text-right">
              Prix
            </th>
          </tr>
        </thead>

        <tbody>
          <% @cart.cart_items.each do |cart_item| %>
            <tr>
              <td class="text-center">
                <%= cl_image_tag cart_item.product.photos.first.key, class: "w-16 h-16 object-cover rounded-lg" %>
              </td>
              <td class="text-left">
                <%= cart_item.product.name %>
              </td>
              <td class="text-right">
                <%= number_to_currency(cart_item.product.price) %>
              </td>
            </tr>
          <% end %>
        </tbody>
        <tfoot>
          <tr>
            <td class="text-left">
              Total
            </td>
            <td class="text-right">
              <%= number_to_currency(@cart.total_price) %>
            </td>
      </table>
    <% else %>
      <p class="text-center">Votre panier est vide</p>
    <% end %>
  </div>

      <%# form version ruby on rails %>
      <%= link_to 'Procéder au paiement', cart_checkout_path(@cart), data: { turbo: "false" }, class: " bg-blue-800 py-2 px-4 rounded-sm transition hover:duration-150 hover:bg-blue-600" %>
</main>

app/views/carts/success.html.erb
<h1>
  Votre commande a bien été enregistrée
</h1>